# Generated by Django 6.0.4 on 2026-05-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('fan', 'Fan'), ('celeb', 'Celeb'), ('manager', 'Manager')], default='fan', max_length=10),
        ),
    ]
