# Generated by Django 6.0.4 on 2026-05-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('fan', 'Fan'), ('celeb', 'Celeb'), ('manager', 'Celeb Manager'), ('staff', 'Staff')], default='fan', max_length=20),
        ),
    ]
