"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-CHANGE_THIS_TO_A_RANDOM_SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = (
    '127.0.0.1', 
    'localhost',
    'celebs-africa-o3zfi.ondigitalocean.app',
    'celebsafrica.com',
    'www.celebsafrica.com'
)
# Static files (CSS, JavaScript, Images)
# Redirect to accounts home after login
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

CSRF_TRUSTED_ORIGINS = [
    'https://www.celebsafrica.com',
    'https://celebsafrica.com',
    'https://celebs-africa-o3zfi.ondigitalocean.app',
]

# Trust the X-Forwarded-Proto header set by the production HTTPS proxy.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Enforce HTTPS-related settings in production only.
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'apps.accounts',
    'apps.celebs',
    'apps.posts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.CanonicalDomainMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.LastSeenMiddleware',
    'core.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.online_users',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'core.backends.CelebManagerBackend',
]


# Database
# htt
# s://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Use PostgreSQL in production (DATABASE_URL env var), SQLite locally
DATABASE_URL = os.environ.get('DATABASE_URL')
db_info = urlparse(DATABASE_URL) if DATABASE_URL else None

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2' if db_info else 'django.db.backends.sqlite3',
        'NAME': db_info.path[1:] if db_info else BASE_DIR / 'db.sqlite3',
        'USER': db_info.username if db_info else '',
        'PASSWORD': db_info.password if db_info else '',
        'HOST': db_info.hostname if db_info else '',
        'PORT': db_info.port if db_info else '',
        'OPTIONS': {'sslmode': 'require'} if db_info else {}
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Keep legacy integer primary keys for existing models and silence W042.
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files — always define MEDIA_ROOT for local dev fallback
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# DigitalOcean Spaces (S3-compatible) for production media storage
AWS_ACCESS_KEY_ID = os.environ.get('SPACES_ACCESS_KEY')
AWS_SECRET_ACCESS_KEY = os.environ.get('SPACES_SECRET_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('SPACES_BUCKET_NAME', '')
AWS_S3_ENDPOINT_URL = os.environ.get('SPACES_ENDPOINT_URL', '')  # e.g. https://fra1.digitaloceanspaces.com
SPACES_CDN_URL = os.environ.get('SPACES_CDN_URL', '').strip()
AWS_DEFAULT_ACL = 'public-read'
AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}

# Serve public media with stable URLs (no query-signature params).
AWS_QUERYSTRING_AUTH = False
AWS_S3_ADDRESSING_STYLE = 'virtual'
AWS_S3_SIGNATURE_VERSION = 's3v4'

_spaces_host = urlparse(AWS_S3_ENDPOINT_URL).netloc if AWS_S3_ENDPOINT_URL else ''
AWS_S3_CUSTOM_DOMAIN = (
    f'{AWS_STORAGE_BUCKET_NAME}.{_spaces_host}'
    if AWS_STORAGE_BUCKET_NAME and _spaces_host
    else ''
)

if SPACES_CDN_URL:
    _cdn = SPACES_CDN_URL.rstrip('/')
    if _cdn.startswith('https://'):
        AWS_S3_CUSTOM_DOMAIN = _cdn[len('https://'):]
    elif _cdn.startswith('http://'):
        AWS_S3_CUSTOM_DOMAIN = _cdn[len('http://'):]
    else:
        AWS_S3_CUSTOM_DOMAIN = _cdn

if AWS_ACCESS_KEY_ID and AWS_STORAGE_BUCKET_NAME:
    # Production: store and serve media via DigitalOcean Spaces
    MEDIA_URL = (
        f'https://{AWS_S3_CUSTOM_DOMAIN}/'
        if AWS_S3_CUSTOM_DOMAIN
        else f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/'
    )
    STORAGES = {
        'default': {'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage'},
        'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
    }
else:
    # Local development: local filesystem + whitenoise for static
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
    }
