# Generated by Django 6.0.2 on 2026-05-09 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Celeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('street_name', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('rating', models.FloatField(default=0.0, help_text='Legacy field; rating now computed from reviews')),
                ('discovered', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/celebs/')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 code', max_length=2, unique=True)),
                ('flag', models.CharField(blank=True, help_text='Flag emoji', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celeb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='celebs.celeb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celeb_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='celeb',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celebs', to='celebs.country'),
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='celebs.category')),
            ],
            options={
                'verbose_name_plural': 'Families',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='celebs.family')),
            ],
            options={
                'unique_together': {('family', 'name')},
            },
        ),
        migrations.AddField(
            model_name='celeb',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='celebs', to='celebs.type'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celeb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='celebs.celeb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('celeb', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celeb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='celebs.celeb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celeb_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('celeb', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celeb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='celebs.celeb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celeb_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('celeb', 'user')},
            },
        ),
    ]
