# Generated by Django 6.0.4 on 2026-04-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('distance', models.FloatField(help_text='Distance from Earth in light years')),
                ('discovered', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
