# Generated by Django 6.0.2 on 2026-04-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stars/'),
        ),
    ]
