# Generated by Django 6.0.4 on 2026-05-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0002_fix_celeb_image_upload_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeb',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
