# Generated by Django 6.0.4 on 2026-05-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0002_star_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='type',
            new_name='street_name',
        ),
        migrations.RemoveField(
            model_name='star',
            name='distance',
        ),
        migrations.AddField(
            model_name='star',
            name='rating',
            field=models.FloatField(default=5, help_text='Rating of the star'),
            preserve_default=False,
        ),
    ]
