# Generated by Django 6.0.4 on 2026-05-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0003_rename_type_star_street_name_remove_star_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/celebs/'),
        ),
    ]
