# Generated by Django 6.0.4 on 2026-05-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0003_add_date_of_death_to_celeb'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeb',
            name='awards',
            field=models.TextField(blank=True, help_text='Notable awards and achievements'),
        ),
        migrations.AddField(
            model_name='celeb',
            name='facebook',
            field=models.CharField(blank=True, help_text='Page name or URL slug', max_length=100),
        ),
        migrations.AddField(
            model_name='celeb',
            name='instagram',
            field=models.CharField(blank=True, help_text='Username only, no @', max_length=100),
        ),
        migrations.AddField(
            model_name='celeb',
            name='net_worth',
            field=models.CharField(blank=True, help_text='e.g. $5 million', max_length=100),
        ),
        migrations.AddField(
            model_name='celeb',
            name='twitter',
            field=models.CharField(blank=True, help_text='Username only, no @', max_length=100),
        ),
        migrations.AddField(
            model_name='celeb',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='celeb',
            name='youtube',
            field=models.CharField(blank=True, help_text='Channel name or URL slug', max_length=100),
        ),
    ]
