# Generated by Django 6.0.4 on 2026-05-13 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0004_add_net_worth_awards_social_to_celeb'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeb',
            name='featured_video',
            field=models.URLField(blank=True, help_text='YouTube video URL e.g. https://www.youtube.com/watch?v=...'),
        ),
        migrations.CreateModel(
            name='CelebPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='celebs/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('celeb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='celebs.celeb')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
