# Generated by Django 6.0.2 on 2026-05-06 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0004_alter_star_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='celebs.star')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='celebs.star')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('star', 'user')},
            },
        ),
    ]
