# Generated by Django 6.0.4 on 2026-05-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0005_add_celebphoto_and_featured_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celeb',
            name='net_worth',
        ),
    ]
