# Generated by Django 6.0.2 on 2026-05-06 04:52

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Star = apps.get_model('celebs', 'Celebs')
    for star in Star.objects.all():
        base_slug = slugify(star.name) or f"star-{star.pk}"
        slug = base_slug
        n = 1
        while Star.objects.filter(slug=slug).exclude(pk=star.pk).exists():
            slug = f"{base_slug}-{n}"
            n += 1
        star.slug = slug
        star.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0005_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, default=''),
            preserve_default=False,
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='star',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
