# Generated by Django 6.0.4 on 2026-05-22 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0008_celebsociallink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='celeb',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='Users (celebs/managers) who can edit this celeb page', related_name='managed_celebs', to=settings.AUTH_USER_MODEL),
        ),
    ]
