# Generated by Django 6.0.2 on 2026-05-06 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0009_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celeb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='celebs.celeb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celeb_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('celeb', 'user')},
            },
        ),
    ]
