# Generated by Django 6.0.2 on 2026-05-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0010_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celeb',
            name='rating',
            field=models.FloatField(default=0.0, help_text='Legacy field; rating now computed from reviews'),
        ),
    ]
