# Generated by Django 5.2.12 on 2026-07-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0010_alter_category_id_alter_celeb_id_alter_celebphoto_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeb',
            name='influence',
            field=models.TextField(blank=True, help_text='Notable influence, impact, or legacy', null=True),
        ),
        migrations.AddField(
            model_name='celeb',
            name='net_worth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated net worth in USD', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='celeb',
            name='spouse',
            field=models.CharField(blank=True, help_text='Name of spouse or partner', max_length=100, null=True),
        ),
    ]
