# Generated by Django 6.0.2 on 2026-05-07 17:52

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Category = apps.get_model('celebs', 'Category')
    SubCategory = apps.get_model('celebs', 'SubCategory')
    for cat in Category.objects.all():
        cat.slug = slugify(cat.name)
        cat.save()
    for sub in SubCategory.objects.all():
        sub.slug = slugify(sub.name)
        sub.save()


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0011_alter_celeb_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
