# Generated by Django 5.2.12 on 2026-08-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0011_celeb_influence_celeb_net_worth_celeb_spouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celeb',
            name='street_name',
            field=models.CharField(blank=True, help_text='Optional street name or nickname for disambiguation', max_length=50, null=True),
        ),
    ]
