# Generated by Django 6.0.2 on 2026-05-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0012_category_slug_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeb',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
