# Generated by Django 6.0.2 on 2026-05-09 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0016_celeb_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celeb',
            name='subcategory',
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='celebs.category')),
            ],
            options={
                'verbose_name_plural': 'Families',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='celebs.family')),
            ],
            options={
                'unique_together': {('family', 'name')},
            },
        ),
        migrations.AddField(
            model_name='celeb',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='celebs', to='celebs.type'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
